# Generated by Django 2.2 on 2019-06-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date_of_birth',
        ),
    ]
