# Generated by Django 2.2 on 2019-08-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userinfo_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='showPhone',
            field=models.BooleanField(default=False),
        ),
    ]
