# Generated by Django 2.2 on 2019-08-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190815_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
