# Generated by Django 2.2 on 2019-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190706_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_seen',
            field=models.BooleanField(default=True),
        ),
    ]
