# Generated by Django 2.2 on 2019-08-15 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='dislike_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikers',
            field=models.ManyToManyField(related_name='dislikers', to=settings.AUTH_USER_MODEL),
        ),
    ]
