# Generated by Django 2.2 on 2019-08-15 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_auto_20190816_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentdisLikers',
            field=models.ManyToManyField(related_name='commentdisLikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike_seen',
            field=models.BooleanField(default=True),
        ),
    ]
